# Generated by Django 3.1.1 on 2020-09-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Aluno')),
                ('born_date', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Rua')),
                ('number', models.SmallIntegerField(blank=True, verbose_name='Número da Casa')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='Primeiro nome do Professor(a)')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='Último nome do Professor(a)')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.SmallIntegerField()),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.teacher')),
            ],
        ),
    ]
