# Generated by Django 3.1.1 on 2020-09-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200922_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
    ]
